# netlify.toml

[build]
  # Define the command to build your project
  command = "npm run build"

  # Define the directory where the build output is located
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-inline-functions-env"

# Configure the service worker behavior
[build.processing]
  # Configure the service worker using Workbox
  [[build.processing.js]]
    # Specify the service worker file to be generated
    entry = "serviceWorker.js"

    # Define caching strategies and options
    [build.processing.js.options]
      # Specify the cache name
      cacheName = "hooks-time-v1"

      # Define URLs to cache
      urls = [
        "/", "/index.html", "/src/Assets/Images/intro"
      ]

      # Define additional options for caching behavior
      # For example:
      # [build.processing.js.options.strategy]
      #   maximumFileSizeToCacheInBytes = 10485760  # 10MB

# Specify additional configuration options for the service worker
[build.environment]
  # Define environment variables if needed
